"""Add support for photo messages.

Revision ID: 119a5dc71f08
Revises: 3083180b71c7
Create Date: 2019-02-09 06:38:31.534935

"""

from alembic import op
import sqlalchemy as sa

revision = '119a5dc71f08'
down_revision = '3083180b71c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('file_id', sa.Text(), nullable=True))
    op.add_column('quote', sa.Column('message_type', sa.Enum('text', 'photo'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'message_type')
    op.drop_column('quote', 'file_id')
    # ### end Alembic commands ###
